id: P006892
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:06.762864
source_metadata:
  id: bdr:W1PD4
  title: མན་ངག་ལྷན་ཐབས་དང་ལྡེ་མིག
  author: ''
  volumes:
    dc983bc349944b7aad1b00b102bec5b5:
      image_group_id: I1PD403
      title: ''
      volume_number: 1
      total_pages: 763
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
